### PR TITLE
Dev rain

### PR DESCRIPTION
**Pull request by RainOrigami**
@DasIschBims pls reformat in jetbrains thing to make commits less whitespace-y, then merge

### CODE REVIEW

**Comment by Bims-sh** [comment]
Tomorrow*!

**Comment by RainOrigami** [comment]
@atsmith14 maybe?

**Comment by Bims-sh** [comment]
I was busy xD, sec

**Comment by Bims-sh** [comment]
@RainOrigami if you wanna delete branch, go ahead

**Pull request merged**
